name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      # NEEDS MORE SETUP
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4

      - name: Terraform Init
        run: terraform init

      # Comment out in the meantime
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve