name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      # Secret
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TF_VAR_site_domain: ${{ secrets.SITE_DOMAIN }}

      # Non-secret
      TF_VAR_error_document: "error.html"
      TF_VAR_index_document: "index.html"
      TF_VAR_environment: "production"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform format check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Plan for PR Comment
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
